/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appletjave;

import static java.lang.Math.pow;
import javax.swing.JOptionPane;
import jdk.nashorn.internal.objects.Global;

/**
 *
 * @author pc lenovo
 */
public class AppletManejadores extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora2
     */
    public AppletManejadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldX = new javax.swing.JTextField();
        jTextFieldY = new javax.swing.JTextField();
        jTextFieldResultado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonSumar = new javax.swing.JButton();
        jButtonRestar = new javax.swing.JButton();
        jButtonMultiplicar = new javax.swing.JButton();
        jButtonXMOD = new javax.swing.JButton();
        jButtonDividir = new javax.swing.JButton();
        jButtonxAy = new javax.swing.JButton();
        jButtonRaizY = new javax.swing.JButton();
        jButtonRaizX = new javax.swing.JButton();
        jButtonYaX = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Resultado");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Y");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldY, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jButtonSumar.setText("+");
        jButtonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumarActionPerformed(evt);
            }
        });

        jButtonRestar.setText("-");
        jButtonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestarActionPerformed(evt);
            }
        });

        jButtonMultiplicar.setText("*");
        jButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicarActionPerformed(evt);
            }
        });

        jButtonXMOD.setText("x mod y ");
        jButtonXMOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXMODActionPerformed(evt);
            }
        });

        jButtonDividir.setText("/");
        jButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDividirActionPerformed(evt);
            }
        });

        jButtonxAy.setText("x a la y");
        jButtonxAy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonxAyActionPerformed(evt);
            }
        });

        jButtonRaizY.setText("Raiz y");
        jButtonRaizY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaizYActionPerformed(evt);
            }
        });

        jButtonRaizX.setText("Raiz x");
        jButtonRaizX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRaizXActionPerformed(evt);
            }
        });

        jButtonYaX.setText("y a la x");
        jButtonYaX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYaXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRaizX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonxAy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRestar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRaizY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButtonYaX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonXMOD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonxAy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonYaX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRaizY, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonRaizX, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonXMOD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumarActionPerformed

        if (jTextFieldX.getText()==null ||jTextFieldX.getText().equals("")) {
            
         JOptionPane.showMessageDialog(null, "Inserte un número en x" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        }else if(jTextFieldY.getText()==null ||jTextFieldY.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Inserte un número en y" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
       }else{
            if (isNumeric()) {
                
        resultado=Double.parseDouble(jTextFieldX.getText())+Double.parseDouble(jTextFieldY.getText());
        jTextFieldResultado.setText(String.valueOf(resultado));
       }
      }
    }//GEN-LAST:event_jButtonSumarActionPerformed

    private void jButtonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestarActionPerformed

         if (jTextFieldX.getText()==null ||jTextFieldX.getText().equals("")) {
            
         JOptionPane.showMessageDialog(null, "Inserte un número en x" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        }else if(jTextFieldY.getText()==null ||jTextFieldY.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Inserte un número en y" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
       }else{
        if (isNumeric()) {
           resultado=Double.parseDouble(jTextFieldX.getText())-Double.parseDouble(jTextFieldY.getText());
        jTextFieldResultado.setText(String.valueOf(resultado));
       }
      }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRestarActionPerformed

    private void jButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicarActionPerformed

  if (jTextFieldX.getText()==null ||jTextFieldX.getText().equals("")) {
            
         JOptionPane.showMessageDialog(null, "Inserte un número en x" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        }else if(jTextFieldY.getText()==null ||jTextFieldY.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Inserte un número en y" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
       }else{
            if (isNumeric()) {
                
        resultado=Double.parseDouble(jTextFieldX.getText())*Double.parseDouble(jTextFieldY.getText());
        jTextFieldResultado.setText(String.valueOf(resultado));
       }
      }


    }//GEN-LAST:event_jButtonMultiplicarActionPerformed

    private void jButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDividirActionPerformed
         if (jTextFieldX.getText()==null ||jTextFieldX.getText().equals("")) {
            
         JOptionPane.showMessageDialog(null, "Inserte un número en x" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        }else if(jTextFieldY.getText()==null ||jTextFieldY.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Inserte un número en y" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
       }else{
            if (isNumeric()) {

          resultado=Double.parseDouble(jTextFieldX.getText())/Double.parseDouble(jTextFieldY.getText());
        //
           if (resultado!=Double.POSITIVE_INFINITY) {
              
            jTextFieldResultado.setText(String.valueOf(resultado));
          }else {
           JOptionPane.showMessageDialog(null, "divisiòn por 0 no  valido" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje     
         }
        
                
        }
      }
    }//GEN-LAST:event_jButtonDividirActionPerformed

    private void jButtonxAyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonxAyActionPerformed
      if (jTextFieldX.getText()==null ||jTextFieldX.getText().equals("")) {
            
         JOptionPane.showMessageDialog(null, "Inserte un número en x" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        }else if(jTextFieldY.getText()==null ||jTextFieldY.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Inserte un número en y" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
       }else{
            if (isNumeric()) {
              resultado=  pow(Double.parseDouble(jTextFieldX.getText()), Double.parseDouble(jTextFieldY.getText()));
            jTextFieldResultado.setText(String.valueOf(resultado));
            }
        }   
        
    }//GEN-LAST:event_jButtonxAyActionPerformed

    private void jButtonYaXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYaXActionPerformed
     
         if (jTextFieldX.getText()==null ||jTextFieldX.getText().equals("")) {
            
         JOptionPane.showMessageDialog(null, "Inserte un número en x" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        }else if(jTextFieldY.getText()==null ||jTextFieldY.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Inserte un número en y" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
       }else{
            if (isNumeric()) {
             resultado=  pow(Double.parseDouble(jTextFieldY.getText()),Double.parseDouble(jTextFieldX.getText()));
            jTextFieldResultado.setText(String.valueOf(resultado));
            }
        }   
        
        
    }//GEN-LAST:event_jButtonYaXActionPerformed

    private void jButtonRaizXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizXActionPerformed

        

        if (jTextFieldX.getText()==null ||jTextFieldX.getText().equals("")) {
            
         JOptionPane.showMessageDialog(null, "Inserte un número en x" ,"información", 
         JOptionPane.WARNING_MESSAGE); 
         
        }else {
             jTextFieldY.setText("0");
            if (isNumeric()) {
              resultado= Math.sqrt(Double.parseDouble(jTextFieldX.getText()));
              jTextFieldResultado.setText(String.valueOf(resultado));  
                     
            }
        
        }
        
    }//GEN-LAST:event_jButtonRaizXActionPerformed

    private void jButtonRaizYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRaizYActionPerformed
 
        
     
           if (jTextFieldY.getText()==null ||jTextFieldY.getText().equals("")) {
            
         JOptionPane.showMessageDialog(null, "Inserte un número en Y" ,"información", 
         JOptionPane.WARNING_MESSAGE); 
        }else {
               
          jTextFieldX.setText("0");   
            if (isNumeric()) {
              resultado= Math.sqrt(Double.parseDouble(jTextFieldY.getText()));
              jTextFieldResultado.setText(String.valueOf(resultado));  
            }
        
        }
        
    }//GEN-LAST:event_jButtonRaizYActionPerformed

    private void jButtonXMODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXMODActionPerformed
    
        
         if (jTextFieldX.getText()==null ||jTextFieldX.getText().equals("")) {
            
         JOptionPane.showMessageDialog(null, "Inserte un número en x" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
        }else if(jTextFieldY.getText()==null ||jTextFieldY.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Inserte un número en y" ,"información", 
         JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
            
       }else{
            if (isNumeric()) {
                
        
             resultado= Double.parseDouble(jTextFieldX.getText())%Double.parseDouble(jTextFieldY.getText());
            
              jTextFieldResultado.setText(String.valueOf(resultado));  
                    
                
              
       
             
         }
        }   
        
        
    }//GEN-LAST:event_jButtonXMODActionPerformed

    private boolean isNumeric(){
	try {
        
             Double.parseDouble(jTextFieldX.getText());
            Double.parseDouble(jTextFieldY.getText());
	  return true;
	} catch (NumberFormatException nfe){
            
          JOptionPane.showMessageDialog(null, "Debe ingresar un número" ,"Error", 
         JOptionPane.ERROR_MESSAGE); //Tipo de mensaje
            
		return false;
	}
}
    
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppletManejadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppletManejadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppletManejadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppletManejadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppletManejadores().setVisible(true);
            }
        });
    }

    
    private double resultado=0.0; 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDividir;
    private javax.swing.JButton jButtonMultiplicar;
    private javax.swing.JButton jButtonRaizX;
    private javax.swing.JButton jButtonRaizY;
    private javax.swing.JButton jButtonRestar;
    private javax.swing.JButton jButtonSumar;
    private javax.swing.JButton jButtonXMOD;
    private javax.swing.JButton jButtonYaX;
    private javax.swing.JButton jButtonxAy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldResultado;
    private javax.swing.JTextField jTextFieldX;
    private javax.swing.JTextField jTextFieldY;
    // End of variables declaration//GEN-END:variables
}
